# Generated by Django 5.0.3 on 2024-05-24 09:01

import app_blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='following_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_owner', models.CharField(max_length=20)),
                ('request_receiver', models.CharField(max_length=20)),
                ('still', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='generate_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='load_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('local_url', models.ImageField(upload_to=app_blog.models.generate_filename)),
                ('current_user_username', models.CharField(max_length=20)),
                ('generated_code', models.IntegerField()),
                ('uploaded_url', models.TextField(default='none')),
            ],
        ),
        migrations.CreateModel(
            name='suggests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_pushed', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('index', models.CharField(max_length=100)),
                ('like_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('image_added', models.BooleanField(default=False)),
                ('generated_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='image_and_specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('generated_code', models.IntegerField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts_image', to='app_blog.load_image')),
                ('specs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts_detail', to='app_blog.user_post')),
            ],
        ),
    ]
