# Generated by Django 5.0.3 on 2024-05-29 12:20

import app_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_image',
            name='local_url',
            field=models.ImageField(blank=True, null=True, upload_to=app_blog.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='load_image',
            name='uploaded_url',
            field=models.TextField(),
        ),
    ]
