# Generated by Django 5.0.3 on 2024-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_image_and_specs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_image',
            name='uploaded_url',
            field=models.TextField(default='none'),
        ),
    ]
